### ISSUE TITLE
Emotes don't work in Youtube Live

### ISSUE THREAD

**Issue by SheinH** [melalawi/GlobalTwitchEmotes#10]
It seems that emotes don't work in YouTube Live chat. Upon futher inspection, they DO work but only in the poplut chat mode for some reason. A fix would be greatly appreciated.
![image](https://cloud.githubusercontent.com/assets/5853497/25573065/b74fb842-2e0f-11e7-96b1-1a1aec473e38.png)

**Comment by melalawi** [comment]
https://github.com/melalawi/GlobalTwitchEmotes/blob/b569b9ec26763dd9fd07f010f2173e59803e2041/src/common/storageHelper.js#L12

Sorry about the delay. I've implemented iframe injection for version 1.3.0, which should fix this issue. Please note that this feature is somewhat experimental.

Version 1.3.0 should be published in a few days.

**Comment by melalawi** [comment]
@SheinH I've pushed the Chrome version of GTE 1.3.0. Let me know if the issue has been resolved.

Firefox and Opera versions will follow shortly.

**Comment by melalawi** [comment]
Firefox version has been pushed. For now, I'll be closing this issue, but if you have any more questions or concerns feel free to reopen it.
