### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by Vidlec** [melalawi/GlobalTwitchEmotes#12]
Getting this error in console:
Uncaught (in promise) Object message: "The message port closed before a reponse was received."

Browser: Chrome 61

Its hard to know from minified js what is causing the error...
Might be this function:
`    function sendMessageToBackground(e) {
            return new Promise(function(n, s) {
                chrome.runtime.sendMessage(e, function(e) {
                    chrome.runtime.lastError ? s(chrome.runtime.lastError) : n(e)
                })
            }
            )
        }`

**Comment by melalawi** [comment]
Hey Vidlec,

This occurs when a message is sent (between the content script and the background script or vice versa) and the [`responseCallback`](https://developer.chrome.com/extensions/runtime#method-sendMessage) method is never called. I've fixed this for version 1.3.0, which should be ready in a few days.

Sorry for the inconvenience.

**Comment by melalawi** [comment]
Version 1.3.0 has been pushed to the Chrome and Firefox stores.

Closing this issue. If you have any other questions or concerns, feel free to reopen this issue or create a new one.
