### ISSUE TITLE
Letting GTE Run on Twitch.tv Itself

### ISSUE THREAD

**Issue by JiMiKi** [melalawi/GlobalTwitchEmotes#13]
Hello, ever since I installed Global Twitch Emotes, I noticed that my chat very often (probably 90% of the time) do not scroll down and keep up with my chats in the Twitch App through Chrome. 

The only way to find out if you got a new message is to scroll down manually at random and find out that there are missed messages, which is extremely frustrating.

Is this something you can look into and/or fix?

Other than this issue, I love your extension!

**Comment by melalawi** [comment]
Are you referring to GTE running on http://www.twitch.tv itself? I'm not 100% sure what the "Twitch App" is. Can you send me a link to it?

**Comment by JiMiKi** [comment]
The Twitch App but in-browser version, app.twitch.tv :)

**Comment by JiMiKi** [comment]
The entire reason why I use the browser version is to get all the emotes that the real Desktop App do not support!

**Comment by melalawi** [comment]
@JiMiKi Which browser are you using? GTE isn't supposed to run on Twitch.tv itself.

**Comment by JiMiKi** [comment]
Chrome, it works fine other than the scrolling issue

**Comment by JiMiKi** [comment]
Or well, it did until i recently refreshed and now for the first time, some emotes are not showing up correctly :S

**Comment by JiMiKi** [comment]
It's not the normal Twitch page, it looks like this https://i.imgur.com/dlBndA0.jpg

**Comment by melalawi** [comment]
I never heard of this downloadable Twitch app. Interesting!

Back to this issue, I'm very surprised that you're seeing emotes at all on Twitch.tv. I've specifically set it such that GTE doesn't run on Twitch.

1) When on Twitch, try clicking on the little 'GTE' button in the top right corner. Does the popup look like this?

<img width="176" alt="GTE BrowserAction" src="https://user-images.githubusercontent.com/6510182/31834431-88bcf57e-b593-11e7-8f44-936ece3cf099.png">

2) Are you using the beta version of Twitch?

**Comment by melalawi** [comment]
Disregard my previous comment, I see what you mean now. 

https://app.twitch.tv/home

**Comment by melalawi** [comment]
What is your use-case for having GTE run on Twitch.tv domains? I'm hesitant on letting GTE run on Twitch for a myriad of reasons. For instance, it could be argued that GTE on Twitch.tv allows for users to make use of subscriber rewards without being subscribed to the given channel.

**Comment by JiMiKi** [comment]
I understand your hesitation, though I doubt it would become much of an issue, as everyone needs to have GTE installed to have the text appear as an emote. 
Considering how few (compared to total viewers on twitch) even use the "popular" BTTV or FFZ Extensions to begin with, I find it hard to believe that enough people would be using GTE for this to become an issue.

My use-case for GTE is to mainly have BTTV and custom emotes specifically on the app.twitch.tv page, used as a standalone chat to send and receive whispers on Twitch. 
This is because I do not watch Twitch streams through a browser at all, but instead using Streamlink + Streamlink Twitch GUI to watch streams in a media player of my preference.

**Comment by j-andrews7** [comment]
You should just allow it to function as usual in these cases, but block subscriber emotes in such cases.

**Comment by melalawi** [comment]
@JiMiKi I understand your point, but I still believe that this dilemma is a Pandora's box that really shouldn't be opened.

I'll probably implement a solution similar to what @j-andrews7 suggested.

**Comment by JiMiKi** [comment]
I understand, this is a viable workaround, I hope this can be fixed soon, it just isn't the same without the emotes!

**Comment by ZeTaurin** [comment]
I can't live without my own emotes in the browser version of Twitch private chat D: so banning paid subscriber emotes on that site is a fair compromise.

**Comment by melalawi** [comment]
I've implemented and pushed this workaround. It should be live within the next few hours.

**Comment by JiMiKi** [comment]
Thanks!

**Comment by JiMiKi** [comment]
Now the BTTV emotes work on app.twitch.tv (worse than they used to, but they work) but the issue I was first reporting, regarding chat getting stuck and not scrolling down automatically when receiving messages with GTE emotes in them, still persists.

To elaborate on the "worse than they used to", the emote shows up for a split second, then for another split second you see the plain text, and then it returns to being an emote again.

**Comment by melalawi** [comment]
Scroll issue has to do with how the inserted emotes cause the chat message's div to grow slightly, which shifts the entire chat upwards. The page interprets this as the user scrolling up slightly, and as such, it freezes the chat in place.

As for the flickering emotes, I'm not 100% sure. I've created a separate issue for this.
