### ISSUE TITLE
GTE sometimes causes chat boxes to lock in place

### ISSUE THREAD

**Issue by melalawi** [melalawi/GlobalTwitchEmotes#16]
> Hello, ever since I installed Global Twitch Emotes, I noticed that my chat very often (probably 90% of the time) do not scroll down and keep up with my chats in the Twitch App through Chrome.
> 
> The only way to find out if you got a new message is to scroll down manually at random and find out that there are missed messages, which is extremely frustrating.
> 
> Is this something you can look into and/or fix?
> 
> Other than this issue, I love your extension!

**Comment by melalawi** [comment]
In chat boxes, replacing text with an emote causes the parent chat message node to grow. This shift propagates up to the chat container, causing the entire chatbox node's `scrollValue` to change slightly. The JavaScript running on the page interprets this as the user scrolling up, which in response, it locks the chat in place.

**Comment by JiMiKi** [comment]
I see... Do you know if there is a way to work around this?

**Comment by melalawi** [comment]
This is a complex issue. Any solution to this would have to be generic (i.e. not retrofitted to a certain chatroom's configuration), otherwise I'd end up having to play cat and mouse whenever a website is changed.

I'll look into this when I can.

**Comment by JiMiKi** [comment]
Yeah I feared that would be the case... I'll keep my fingers crossed and hope it works out some day!

**Comment by melalawi** [comment]
I did a bit of experimenting and came up with a possible solution, but it needs work. Would you like to test it @JiMiKi?

If so, send me an email at mohamed.y.elalawi@gmail.com

**Comment by melalawi** [comment]
Resolving until this proves itself to be an issue again.
