### ISSUE TITLE
Store emotes locally?

### ISSUE THREAD

**Issue by hugomg** [melalawi/GlobalTwitchEmotes#2]
GlobalTwitchEmotes currently works by replacing emote text with images that link to static-cdn.jtvnw.net. If you use an emote that is not cached, GTE will make Firefox send a network request for the image, which will leak to Twitch (via the Referer header) the URL of the website you are currently visiting.

If the images were saved locally, pages would have to do less network requests and it would also avoid the privacy issue I mentioned.

**Comment by melalawi** [comment]
I've definitely been thinking about doing something like this. From the looks of it, Chrome makes this task relatively trivial:

https://developer.chrome.com/apps/offline_storage

It's the Firefox implementation that has left me feeling skittish, however. I'll definitely take a crack at it when I'm a bit more free next week.

**Comment by melalawi** [comment]
I looked into what it would take to implement this, and it would essentially involve storing each emote's base64 format and using that as the \<img\>'s src as opposed to the simple url. Unfortunately the performance hit that comes with converting each emote, in addition to the amount of storage space necessary to store these values, would quickly get out of control. I don't think there's a feasible way of doing this.

I'll keep thinking about it, and I'll reopen this issue if I come up with something.
