### ISSUE TITLE
GTE not saving settings on Firefox 57

### ISSUE THREAD

**Issue by agenttud** [melalawi/GlobalTwitchEmotes#20]
Hey!

I recently transitioned to Firefox 57 and, while the extension is supported, it does not save any settings. Moreover, the popup does not display the filter mode and how "the page currently is".
![gte](https://user-images.githubusercontent.com/18105477/33155903-ce28e5ca-cff4-11e7-88ca-baee8fcae67d.png)

**Comment by melalawi** [comment]
Hey @agenttud 

Are you able to export your GTE settings via the options page? I'd like to take a look at them.

Thanks.

**Comment by agenttud** [comment]
Here is the export file (with default settings).

[GTESettings.txt](https://github.com/melalawi/GlobalTwitchEmotes/files/1499857/GTESettings.txt)

If I try to save some settings and then export, I get a smaller file (in this example, with emojis checked and twitch.tv emotes and channel emotes checked).

[GTESettings2.txt](https://github.com/melalawi/GlobalTwitchEmotes/files/1499863/GTESettings2.txt)

**Comment by melalawi** [comment]
Nothing seems odd about the settings you've provided. Try following these steps:

1. Type **about:debugging** into your address bar and hit enter.
2. Check the box labelled **Enable add-on debugging**.
3. Scroll down to Global Twitch Emotes and click its **debug** link.
4. A window should appear, followed by a prompt. Click **OK** on the prompt.
5. In the new window, click on the **Console** tab.
6. You should see a bunch of filter options. Ensure that only **Net** and **JS** are enabled, as such:
<img width="309" alt="Debug console filter options" src="https://user-images.githubusercontent.com/6510182/33186614-6231b534-d050-11e7-86c6-bcb182ebfdda.png">
7. Upload a screenshot of the entire console window here.

Thanks.

**Comment by agenttud** [comment]
![gte p1](https://user-images.githubusercontent.com/18105477/33187159-2806639c-d090-11e7-8c3f-f548d5e1f344.JPG)
![gte p2](https://user-images.githubusercontent.com/18105477/33187160-2a164724-d090-11e7-91ee-fd7c819a1fe8.JPG)
![gte p3](https://user-images.githubusercontent.com/18105477/33187161-2bd03142-d090-11e7-9c44-b7ed1e0ab825.JPG)
![gte p4](https://user-images.githubusercontent.com/18105477/33187163-2d61d9b6-d090-11e7-95b8-666e3a5b911f.JPG)

The highlight are only relevant to see the positioning of the page, because I couldn't screenshot the whole page at once and there are few unique marks that could guide you.

There are also a bunch of Security errors, but I didn't include them.

**Comment by agenttud** [comment]
Any idea as to why this is happening?

**Comment by melalawi** [comment]
@agenttud is this still happening? I pushed 1.4.0 to the addon store today.

**Comment by agenttud** [comment]
@melalawi it got fixed a while ago. I think I created a new Firefox profile and migrated everything. That fixed it, IIRC.

However, since you're active again after a long while, can you update it so that it displays regular Twitch emotes again. I believe Twitch API changed at the beginning of this year. If you want another thread for that issue, I could make one, but I don't know how to explain the technical API stuff.

**Comment by melalawi** [comment]
> However, since you're active again after a long while, can you update it so that it displays regular Twitch emotes again. I believe Twitch API changed at the beginning of this year. If you want another thread for that issue, I could make one, but I don't know how to explain the technical API stuff.

Just did, @agenttud :)

Pull the latest update from the Firefox store and it should work. Sorry for the delay.
