### ISSUE TITLE
Add `PRE` to the list of illegal tag names

### ISSUE THREAD

**Issue by WorldSEnder** [melalawi/GlobalTwitchEmotes#22]
Often when I browse coding sites, they format code in `<pre>` elements. Quoting the HTML standard: "structure is represented by typographic conventions rather than by elements" implies in my opinion that text in these elements should be exempt from emote replacement.

Another possibility is to exempt more specifically the `CODE`, `KBD` and `SAMP`, `VAR` elements.

https://github.com/melalawi/GlobalTwitchEmotes/blob/b7963b2d2eafdc9153ad528edb47ecbf8ac2266f/src/common/contentscript/js/pageObserver.js#L10-L12

**Comment by melalawi** [comment]
I believe this would confuse a lot of users. The overwhelming majority of GTE users are not familiar with the HTML standard.

Maybe an option to specify your own element types to ignore would suffice?
