### ISSUE TITLE
Emotes not being cached

### ISSUE THREAD

**Issue by blueYOSHI9000** [melalawi/GlobalTwitchEmotes#24]
Lately emotes haven't being showing up at all, even after closing the browser, turning the extension on and off and even exporting and importing settings. I found out that there weren't any cached emote sets ([image](https://i.imgur.com/IwWFJP8.png)).
Could there be a button to force-reload emote sets instead of waiting until it does so automatically?

**Comment by blueYOSHI9000** [comment]
Update: Re-installing the extension worked. But also only if I *didn't* import the backup so it seems that emotes don't get cached after importing settings?
Using Brave if that's important, should be the same as Chrome tho'.

**Comment by melalawi** [comment]
Is this still an issue?

**Comment by melalawi** [comment]
I can't seem to reproduce this issue. @blueYOSHI9000 if you find it happening again please feel free to open a new issue and I'll dig into it :)
