### ISSUE TITLE
Twitch emotes no longer work

### ISSUE THREAD

**Issue by fiveofeight** [melalawi/GlobalTwitchEmotes#25]
Twitchemotes has depreciated and removed the v3 api, which means that the addon is no longer to pull data for twitch global/channel emotes, only FFZ and BTTV emotes show up now.

**Comment by Be1con** [comment]
I got that problem as well.

**Comment by bengrebe** [comment]
I have this issue as well I can't use any vanilla twitch emotes

**Comment by melalawi** [comment]
Sorry for the delay. Fixed in 96ae8a30c90201dce15007596d89985832e1dfa6

**Comment by fiveofeight** [comment]
Thanks for the update!  Are you planning on resubmitting it to the Mozilla addon site or a signed version of 1.4, since only Firefox ESR, Developer, and Nightly can install unsigned addons.
