### ISSUE TITLE
Firefox removed the addon?

### ISSUE THREAD

**Issue by Erfie** [melalawi/GlobalTwitchEmotes#26]
I can no longer download the addon for firefox https://addons.mozilla.org/en-US/firefox/addon/globaltwitchemotes/

**Comment by melalawi** [comment]
I'm working with Mozilla reviewers to republish the extension. Apologies for the disruption.

**Comment by melalawi** [comment]
The extension [is now available](https://addons.mozilla.org/en-US/firefox/addon/globaltwitchemotes/). However, the Firefox reviewers have provided me with additional feedback. I'll continue working with them.

**Comment by Erfie** [comment]
For whatever reason mozilla removed the addon yet again :/
