### ISSUE TITLE
GTE broken in Firefox 75/76

### ISSUE THREAD

**Issue by agenttud** [melalawi/GlobalTwitchEmotes#28]
I updated to Firefox 75/76 and now I have basically the [same problem as 2+ years ago](https://github.com/melalawi/GlobalTwitchEmotes/issues/20).

Extension has everything disabled and doesn't save any changes. The menu looks like this: 

![image](https://user-images.githubusercontent.com/18105477/81269824-2de23300-904a-11ea-97ec-37deedeb776f.png)

Going into debugging, it looks like this (first 2 are from Firefox 75, then I updated to 76, since I thought that might help):

![image](https://user-images.githubusercontent.com/18105477/81269104-266e5a00-9049-11ea-9da3-fc6cc0e087e9.png)

![image](https://user-images.githubusercontent.com/18105477/81269172-3ede7480-9049-11ea-9c7c-48c7683a27ba.png)

![image](https://user-images.githubusercontent.com/18105477/81269619-dc39a880-9049-11ea-935a-6a7cfd0a5aab.png)

IIRC, the way I fixed it last time was to create a whole new profile and migrate everything, but it takes so long to set everything up again...

**Comment by melalawi** [comment]
Sorry about that! If I understand your issue, it should be fixed in 2ff845878467bc0c1d1ec52541c28afe91fc56ac.

Twitch.tv [made OAuth a requirement in their APIs](https://twitter.com/TwitchDev/status/1256274739947061249) as of a few hours ago. This caught me off-guard.

Your extension should automatically update within 24 hours. Let me know if the issue persists.

**Comment by agenttud** [comment]
Yea, the new version works like before. Thanks!

**Comment by fiveofeight** [comment]
Still seem to be having issues with version 1.4.1005 on Firefox 76. Whenever I go to settings, its empty and has no channels added.  I add some and save them, then reopen settings and they're gone again. If I try saving my settings and exporting them, they seem to export fine, but when I import them they show up only till I close my settings page, and then they vanish again.
![image](https://user-images.githubusercontent.com/1911527/81390212-1017db00-90e9-11ea-8aa3-cce27ab043e4.png)
[GTESettings.txt](https://github.com/melalawi/GlobalTwitchEmotes/files/4598033/GTESettings.txt)

**Comment by Yoshiman5551** [comment]
Same issue

**Comment by Electrolyte220** [comment]
I'm not sure I'm able to fix this, as it would require signing the addon, which I do not have access to.

You can try [this](https://github.com/melalawi/GlobalTwitchEmotes/blob/master/README.md#installation) if you want.
