### ISSUE TITLE
Problems with SSL

### ISSUE THREAD

**Issue by terratronix** [melalawi/GlobalTwitchEmotes#3]
The Twitchemote.com API doesn't provide HTTPS links which leads to the browser thinking the site is not secure when emotes are loaded. A. change to https if possible B. if not, contact twitchemotes if they want to change to make https the default

**Comment by melalawi** [comment]
Hey terratronix,

twitchemotes has updated their API to use HTTPS, and as of 9da9e84 (version 1.1.1020), Global Twitch Emotes now makes requests to this new API.

**Comment by terratronix** [comment]
Hey,

Thanks for the response. I was looking into this and contacted twitchemotes
and the guy told me the new api is protocol less. Thanks for updating
really enjoy the plugin. Wanted to do this on myself as a fun project and
thought no-one had the idea before me but I guess I was wrong :D
Nice work ! Have a nice day
Am 11.02.2016 01:54 schrieb "Mohamed" <notifications@github.com>:
