### ISSUE TITLE
Not all bttv emotes are loading due to API V2

### ISSUE THREAD

**Issue by fiveofeight** [melalawi/GlobalTwitchEmotes#30]
Not all bttv emotes are being loaded due to the use of bttv's api V2 it seems. V2 API gives Error 1020. https://community.nightdev.com/t/bttv-api-changed/26248

For example, for xqc's channel it only cached these emotes 
 `bttvChannels:xqcow:"{"set":"bttvChannels:xqcow","emotes":{"FeelsRectangleMan":{"url":"https://cdn.betterttv.net/emote/58661a9573f26556fc930080/1x","channel":"BetterTTV Emote"},"xqcPls":{"url":"https://cdn.betterttv.net/emote/5b021b28cc53cd6c27c99331/1x","channel":"BetterTTV Emote"},"HAMMERS":{"url":"https://cdn.betterttv.net/emote/5b3552a33b9b244c651c7756/1x","channel":"BetterTTV Emote"},"xqcCD":{"url":"https://cdn.betterttv.net/emote/5b875b589337c17bd86677f1/1x","channel":"BetterTTV Emote"}},"date":1589327065627}"`

API v3 shows all the emotes properly: https://api.betterttv.net/3/cached/users/twitch/71092938
https://github.com/Chatterino/chatterino2/pull/1278/commits/39231fc87fc7370597fe3bd3fde37606deae8f0e

**Comment by melalawi** [comment]
90921f03fd8617ef4e020f9df36ae4e06c5fd7d0

Fixed. Sorry for the delay!

**Comment by fiveofeight** [comment]
Awesome, thanks for the fix! I just updated and cleared the cached bttv emotes, it's working properly now.
