### ISSUE TITLE
Cannot import/change settings on Chrome

### ISSUE THREAD

**Issue by Serfin** [melalawi/GlobalTwitchEmotes#31]
While I'm trying to import settings into Chrome (it also does not work while i'm trying to change options by myself), these two errors occurs

- Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
- Error handling response: TypeError: Cannot read property 'header' of undefined

```javascript 

3: [function(require, module, exports) {
        var browser = require("browser");
        function MessageClient() {
            var e = null;
            function s(s) {
                e && e(s)
            }
```

```javascript

function onMessage(e) {
    "allEmotes" === e.header && (client.stopListening(),
    loadEmoteSetsIntoTable(e.payload))
}

```

e is undefined at this point, (options.js at line 4137)

![image](https://user-images.githubusercontent.com/23151526/82757390-720e5b00-9de0-11ea-8987-57889ece7e4d.png)

Version 81.0.4044.138 (Official version) (64-bits)
Windows 10

**Comment by melalawi** [comment]
59e98ae1ace0250b972071c39756ea7b47f1eba0

I have pushed an update. Let me know if this continues happening in 24 hours.

Sorry for the delay!

**Comment by Serfin** [comment]
Works like a charm, thanks for the update!
