### ISSUE TITLE
Doesn't replace emotes in Microsoft Teams Chat 

### ISSUE THREAD

**Issue by douglance** [melalawi/GlobalTwitchEmotes#37]
This extension is not working for Microsoft Teams chat. I tried to look through the console for warnings or errors, but I didn't see anything relevant. 

It looks like Microsoft Teams is an Angular app, so the extension should be able to work with it. 

You should be able to sign up for a free account to test it. Let me know if there's anything I can do to help you get this working. Thanks!

**Comment by Jordang3177** [comment]
I need this in my life, please PepeHands

**Comment by melalawi** [comment]
Sorry for the admittedly long delay. This already works! 

Please follow the instructions here:

>[Global Twitch Emotes Doesn't Work in YouTube Live/Facebook Chat/Some Other Thing!](https://ostrichtools.com/p/GlobalTwitchEmotes#Iframe)
Try enabling the [Experimental Iframe Support](https://ostrichtools.com/images/projects/gte/howToYouTube.gif) option in the settings.
