### ISSUE TITLE
Settings in Chrome don't show up, can't set up anything

### ISSUE THREAD

**Issue by Charelene** [melalawi/GlobalTwitchEmotes#4]
As just mentioned in the title. Screenshot included. The thing is, that it's fine to have common emotes at least, but I need BTTV and Subscribers emotes.
![image](https://cloud.githubusercontent.com/assets/12827721/14763251/f339e77a-0998-11e6-843a-acef812d318e.png)

**Comment by terratronix** [comment]
It might be, that one of your chrome extensions is causing this to happen. 
List your extensions or try starting chrome with only GTE active.

**Comment by Charelene** [comment]
@terratronix i think not. 
I've only got  BTTV and Adblock, it earlier worked, but not now.

**Comment by melalawi** [comment]
Version 1.2.0 should alleviate this problem. Sorry for the delay.
