### ISSUE TITLE
7tv emotes not displaying correctly

### ISSUE THREAD

**Issue by rsoltesz** [melalawi/GlobalTwitchEmotes#54]
While using the experimental iframe support in the web version of Teams, some 7tv emotes have stopped displaying correctly in the last 2-3 weeks, instead displaying a broken image thumbnail. Happening in both Chrome and Edge. Not all 7tv emotes seem to have this issue - maybe related to an update?

**Comment by ms-dc** [comment]
This is still a thing apparently. BTTV is fine (not sure about FFZ, probably fine as well) but 7tv is always broken.
