### ISSUE TITLE
getClassName fails if SVG element has no class

### ISSUE THREAD

**Issue by devilesk** [melalawi/GlobalTwitchEmotes#6]
`node.className.baseVal || node.className` returns the node.className object when node.className.baseVal is an empty string

https://github.com/melalawi/GlobalTwitchEmotes/blob/4e555d284ce3d35650b50bfc503fc28c14273414/src/common/contentscript/pageObserver.js#L98

**Comment by melalawi** [comment]
This is a pretty bad oversight on my part. Thanks for pointing this out, I'll be pushing a fix shortly.

**Comment by melalawi** [comment]
https://github.com/melalawi/GlobalTwitchEmotes/blob/master/src/common/contentscript/pageObserver.js#L94

Fixed, thanks for the help!
