### ISSUE TITLE
Emotes not being displayed.

### ISSUE THREAD

**Issue by Busti** [melalawi/GlobalTwitchEmotes#7]
What can I say.
Emotes are not being displayed for me.
I also can't really provide any steps to reproduce this other than installing the extension.

![oetjvtf 1](https://cloud.githubusercontent.com/assets/3575167/21786494/692c0cbc-d6c4-11e6-8448-6d5f38c11841.png)

**Comment by melalawi** [comment]
Hey Busti,

On a page where this issue is present, please press F12, click on the 'console' tab of the window that appears, and post a screenshot here.

![chrome_2017-01-09_17-19-07](https://cloud.githubusercontent.com/assets/6510182/21787632/dbbb3b20-d68f-11e6-9299-ec0f1e4b9ee1.png)

Thanks.

**Comment by Busti** [comment]
I have had this bug for a couple months, but when I am googleing "Kappa" right now it seems to work perfectly well.
I will update when it occurs again.

**Comment by melalawi** [comment]
I've been looking into possible causes of this issue and pushed a minor bugfix update last night. Perhaps this addressed your problem?

**Comment by melalawi** [comment]
I'll be closing this issue, now that it seems your problem was resolved. Feel free to open another issue if this reoccurs.

Thanks.
