### ISSUE TITLE
Firefox/Chrome stutter

### ISSUE THREAD

**Issue by billbatista** [melalawi/GlobalTwitchEmotes#8]
Hi! I've been using your addon for a long time on Firefox and after the last update my Firefox started stuttering at random times. By disabling one addon at a time, it looks like it's GTE fault. I also have friends witht he same problem, but using Chrome.

What kind of tests can I do to help you find the issue?

**Comment by melalawi** [comment]
Are there certain websites you guys visit where this occurs frequently?

**Comment by billbatista** [comment]
I can't think of specific websites, it happens globally. Doesn't matter if I have 1 or 15 tabs opens either.

**Comment by luastoned** [comment]
Browsing GitHub (or having 20+ tabs open) pretty much grinds FireFox to a halt with the addon installed.

**Comment by melalawi** [comment]
Very sorry about the delay.

I've hauled over a lot of the heavier work of this extension to the background script for version 1.3.0 in an attempt to combat this issue. Early results are promising.

I'll be publishing the update within the next few days.

**Comment by melalawi** [comment]
Version 1.3.0 has been pushed to the Chrome Web Store and the Mozilla Addon Store.

I'll leave this issue open until it is confirmed that the performance issues have been fixed.

**Comment by melalawi** [comment]
Closing this issue. If you guys still notice performance problems, feel free to reopen this issue or create a new one.

Thank you.
