### ISSUE TITLE
Blacklist isn't working properly

### ISSUE THREAD

**Issue by YvesW** [melalawi/GlobalTwitchEmotes#9]
I've been trying to blacklist emotes from hireztv on FF 51.0.1 (64-bit) [as you can see](https://i.imgur.com/TLNo4ik.png); however, text still gets converted to his emotes.

[Example](https://i.imgur.com/gh2XMwD.png) from https://www.reddit.com/r/Competitiveoverwatch/comments/5u7pvv/c9_vs_af_blue_apex_analysis_by_flame/
[Example](https://i.imgur.com/FkpDGEq.png) from https://en.wikipedia.org/wiki/Doctor_Strange_(film)#Plot

Would love it if it could be fixed; thanks in advance.

Yves

**Comment by melalawi** [comment]
Very sorry about the delay.

I've refactored the emote filtering code. In addition, version 1.3.0 will require that users select the subscriber emotes they want to see, which in itself is another solution to this problem.

Update will be published in the next few days.

**Comment by melalawi** [comment]
Update has been pushed to the Firefox and Chrome extension stores.

@YvesW let me know if you have any more concerns.

**Comment by melalawi** [comment]
Closing this issue. Feel free to open a new one if you run into this problem in the future.
